"""Render the complete original/proposed Markdown comparison without network access.

The baseline is the linked HackMD download captured on 2026-09-08. The generated
Markdown is a lossless line diff; the HTML uses the existing review presentation.
"""

from difflib import SequenceMatcher
from hashlib import sha256
from html import escape
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
original = (DOCS / "reference/kong-allocation-history-spec-original.md").read_text()
proposed = (DOCS / "kong-allocation-history-spec-proposed.md").read_text()
old_lines = original.splitlines()
new_lines = proposed.splitlines()


def code_flags(lines):
    inside = False
    result = []
    for line in lines:
        if line.startswith("```"):
            result.append("fence")
            inside = not inside
        else:
            result.append("code" if inside else "text")
    assert not inside, "Unclosed Markdown code fence"
    return result


def inline(value):
    value = escape(value)
    value = re.sub(r"`([^`]+)`", r"<code>\1</code>", value)
    value = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', value)
    return re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", value)


old_flags, new_flags = code_flags(old_lines), code_flags(new_lines)
rows = []
for tag, a, b, c, d in SequenceMatcher(None, old_lines, new_lines, autojunk=False).get_opcodes():
    if tag == "equal":
        rows.extend((" ", old_lines[i], old_flags[i]) for i in range(a, b))
    else:
        if tag in ("delete", "replace"):
            rows.extend(("-", old_lines[i], old_flags[i]) for i in range(a, b))
        if tag in ("insert", "replace"):
            rows.extend(("+", new_lines[i], new_flags[i]) for i in range(c, d))

assert [text for kind, text, _ in rows if kind != "+"] == old_lines
assert [text for kind, text, _ in rows if kind != "-"] == new_lines
header = [
    "# Vault Allocation History — Proposed Redline of Kong #396",
    "",
    "Original: https://hackmd.io/@murderteeth/rJkQlX-AWx (snapshot captured 2026-09-08).",
    "",
    "Generated by `python3 scripts/render-kong-spec-redline.py`. Source L# refers to this combined diff.",
    "",
    "````diff",
]
(DOCS / "kong-allocation-history-spec-redline.md").write_text(
    "\n".join(header + [(kind + text).rstrip() for kind, text, _ in rows] + ["````", ""])
)

output = [
    '<div class="diff-row context-block"><div class="content"><p>Generated from the complete original and current proposed specifications. '
    f'Original SHA-256: <code>{sha256(original.encode()).hexdigest()[:12]}</code>; '
    f'proposed SHA-256: <code>{sha256(proposed.encode()).hexdigest()[:12]}</code>.</p></div></div>'
]
in_code = False
for number, (kind, text, flag) in enumerate(rows, len(header) + 1):
    if flag == "fence":
        continue
    if not text.strip() and flag != "code":
        continue
    addition = kind == "+"
    removal = kind == "-"
    css = "add-block" if addition else "remove-block" if removal else "context-block"
    label = "Added" if addition else "Removed" if removal else "Unchanged"
    if flag == "code":
        if not in_code:
            output.append('<div class="code-block">')
            in_code = True
        code_css = "addition" if addition else "removal" if removal else "context-line"
        output.append(
            f'<div class="code-line {code_css}" title="Combined redline source L{number}">'
            '<span class="code-marker" aria-hidden="true"></span>'
            f'<span class="code-text">{escape(text) or " "}</span></div>'
        )
        continue
    if in_code:
        output.append("</div>")
        in_code = False
    heading = re.match(r"^(#{1,4})\s+(.+)", text)
    if heading:
        level = min(len(heading[1]) + (len(heading[1]) == 1), 4)
        label_text = inline(heading[2])
        content = f'<h{level} class="section-heading">{("<del>" + label_text + "</del>") if removal else label_text}</h{level}>'
    else:
        label_text = inline(text)
        content = f'<p>{("<del>" + label_text + "</del>") if removal else label_text}</p>'
    output.append(
        f'<div class="diff-row {css}"><span class="gutter" aria-hidden="true"></span>'
        f'<div class="content" style="padding-left: 4px">{content}'
        f'<span class="line-ref" aria-hidden="true" title="Combined redline Markdown source line {number}">'
        f'source L{number}</span><span class="sr-only">{label} line</span></div></div>'
    )
if in_code:
    output.append("</div>")

target = DOCS / "kong-allocation-history-spec-redline.html"
html = target.read_text()
start = "<!-- BEGIN GENERATED REDLINE -->"
end = "<!-- END GENERATED REDLINE -->"
assert html.count(start) == html.count(end) == 1
prefix, tail = html.split(start)
_, suffix = tail.split(end)
target.write_text(prefix + start + "\n" + "\n".join(output) + "\n" + end + suffix)
print(f"Rendered {len(rows)} diff lines; both original and proposed reconstruct exactly.")
